export const LANGUAGES = {
  malagasy: { name: "Malagasy", flag: "fi fi-mg" },
  sakalava: { name: "Sakalava", flag: "fi fi-mg" },
  kibushi: { name: "Kibushi", flag: "fi fi-mg" },
  shimaore: { name: "Shimaore", flag: "fi fi-yt" },
  creole_reunionnais: { name: "Créole réunionnais", flag: "fi fi-fr" },
  allemand: { name: "Allemand", flag: "fi fi-de" },
  anglais: { name: "Anglais", flag: "fi fi-gb" },
  espagnol: { name: "Espagnol", flag: "fi fi-es" },
  italien: { name: "Italien", flag: "fi fi-it" },
  japonais: { name: "Japonais", flag: "fi fi-jp" },
  portugais_bresil: { name: "Portugais (Brésil)", flag: "fi fi-br" },
  lingala: { name: "Lingala", flag: "fi fi-cd" },
  wolof: { name: "Wolof", flag: "fi fi-sn" },
  swahili: { name: "Swahili", flag: "fi fi-cd" },
  mandarin: { name: "Mandarin", flag: "fi fi-cn" },
};

export const THEMES = [
  {
    id: "01-anglais-hello",
    title: "Bonjour",
    icon: "waving_hand",
    url: "/category",
  },
  {
    id: "02-anglais-relatives",
    title: "Les proches",
    icon: "groups",
    url: "/category",
  },
  {
    id: "03-anglais-family",
    title: "Ma famille",
    icon: "diversity_3",
    url: "/category",
  },
  {
    id: "04-anglais-have-be",
    title: "Avoir et être",
    icon: "language",
    url: "/category",
  },
  {
    id: "05-anglais-in-the-cafe",
    title: "Au café",
    icon: "local_cafe",
    url: "/category",
  },
  {
    id: "06-anglais-restaurant",
    title: "Au restaurant",
    icon: "restaurant",
    url: "/category",
  },
  {
    id: "07-anglais-want",
    title: "Vouloir",
    icon: "favorite",
    url: "/category",
  },
  {
    id: "08-anglais-plats",
    title: "Les plats",
    icon: "dinner_dining",
    url: "/category",
  },
  {
    id: "09-anglais-day-month",
    title: "Les jours et les mois",
    icon: "calendar_month",
    url: "/category",
  },
  {
    id: "10-anglais-time-numbers",
    title: "L'heure et les nombres",
    icon: "schedule",
    url: "/category",
  },
  {
    id: "11-anglais-rdv",
    title: "Les Rendez-vous",
    icon: "event",
    url: "/category",
  },
  {
    id: "12-anglais-on_the_telephone",
    title: "Au téléphone",
    icon: "call",
    url: "/category",
  },
  {
    id: "13-anglais-at_the_ticket_office",
    title: "À la billetterie",
    icon: "confirmation_number",
    url: "/category",
  },
  {
    id: "14-anglais-to_go_and_to_take",
    title: "Aller et prendre",
    icon: "directions_walk",
    url: "/category",
  },
  {
    id: "15-anglais-public _transportation",
    title: "Public  transportation",
    icon: "directions_bus",
    url: "/category",
  },
  {
    id: "16-anglais-on_the_road",
    title: "Sur la route",
    icon: "directions_car",
    url: "/category",
  },
  {
    id: "17-anglais-about_town",
    title: "En ville",
    icon: "location_city",
    url: "/category",
  },
  {
    id: "18-anglais-finding_your_way",
    title: "S'orienter",
    icon: "explore",
    url: "/category",
  },
  {
    id: "19-anglais-sightseeing",
    title: "Visites touristiques",
    icon: "photo_camera",
    url: "/category",
  },
  {
    id: "20-anglais-at_the_airport",
    title: "À l'aéroport",
    icon: "flight",
    url: "/category",
  },
  {
    id: "21-anglais-booking_a_room",
    title: "Réserver une chambre",
    icon: "calendar_month",
    url: "/category",
  },
  {
    id: "22-anglais-in_the_hotel",
    title: "À l'hôtel",
    icon: "hotel",
    url: "/category",
  },
  {
    id: "23-anglais-camping",
    title: "Camping",
    icon: "cabin",
    url: "/category",
  },
  {
    id: "24-anglais-descriptions",
    title: "Descriptions",
    icon: "description",
    url: "/category",
  },
  {
    id: "25-anglais-shopping",
    title: "Achats",
    icon: "shopping_cart",
    url: "/category",
  },
  {
    id: "26-anglais-at_the_market",
    title: "Au marché",
    icon: "storefront",
    url: "/category",
  },
  {
    id: "27-anglais-at_the_supermarket",
    title: "Au supermarché",
    icon: "local_mall",
    url: "/category",
  },
  {
    id: "28-anglais-clothes and shoes",
    title: "Vêtements et chaussures",
    icon: "checkroom",
    url: "/category",
  },
  {
    id: "29-anglais-jobs",
    title: "Emplois",
    icon: "work",
    url: "/category",
  },
  {
    id: "30-anglais-the_office",
    title: "Au bureau",
    icon: "business_center",
    url: "/category",
  },
  {
    id: "31-anglais-academic_world",
    title: "Monde académique",
    icon: "school",
    url: "/category",
  },
  {
    id: "32-anglais-in_business",
    title: "Dans les affaires",
    icon: "trending_up",
    url: "/category",
  },
  {
    id: "33-anglais-at_the_pharmacy",
    title: "À la pharmacie",
    icon: "local_pharmacy",
    url: "/category",
  },
  {
    id: "34-anglais-the_body",
    title: "Le corps",
    icon: "emoji_people",
    url: "/category",
  },
  {
    id: "35-anglais-at_the_doctor",
    title: "Chez le médecin",
    icon: "medical_services",
    url: "/category",
  },
  {
    id: "36-anglais-at_the_hospital",
    title: "À l'hôpital",
    icon: "emergency",
    url: "/category",
  },
  {
    id: "37-anglais-at_home",
    title: "À la maison",
    icon: "home",
    url: "/category",
  },
  {
    id: "38-anglais-in_the_house",
    title: "Dans la maison",
    icon: "bedroom_parent",
    url: "/category",
  },
  {
    id: "39-anglais-the_backyard",
    title: "Le jardin",
    icon: "grass",
    url: "/category",
  },
  {
    id: "40-anglais-pets",
    title: "Animaux domestiques",
    icon: "pets",
    url: "/category",
  },
  {
    id: "41-anglais-post_office_and_bank",
    title: "Poste et banque",
    icon: "account_balance",
    url: "/category",
  },
  {
    id: "42-anglais-services",
    title: "Services",
    icon: "build",
    url: "/category",
  },
  {
    id: "43-anglais-to_come",
    title: "À venir",
    icon: "event_upcoming",
    url: "/category",
  },
  {
    id: "44-anglais-police_and_crime",
    title: "Police et crime",
    icon: "local_police",
    url: "/category",
  },
  {
    id: "45-anglais-leisure_time",
    title: "Temps libre",
    icon: "movie",
    url: "/category",
  },
  {
    id: "47-anglais-socializing",
    title: "Socialisation",
    icon: "group_add",
    url: "/category",
  },
  {
    id: "25-anglais-shopping",
    title: "Achats",
    icon: "shopping_cart",
    url: "/category",
  },
  {
    id: "26-anglais-at_the_market",
    title: "Au marché",
    icon: "storefront",
    url: "/category",
  },
  {
    id: "27-anglais-at_the_supermarket",
    title: "Au supermarché",
    icon: "local_mall",
    url: "/category",
  },
  {
    id: "28-anglais-clothes and shoes",
    title: "Vêtements et chaussures",
    icon: "checkroom",
    url: "/category",
  },
  {
    id: "29-anglais-jobs",
    title: "Emplois",
    icon: "work",
    url: "/category",
  },
  {
    id: "30-anglais-the_office",
    title: "Au bureau",
    icon: "business_center",
    url: "/category",
  },
  {
    id: "31-anglais-academic_world",
    title: "Monde académique",
    icon: "school",
    url: "/category",
  },
  {
    id: "32-anglais-in_business",
    title: "Dans les affaires",
    icon: "trending_up",
    url: "/category",
  },
  {
    id: "33-anglais-at_the_pharmacy",
    title: "À la pharmacie",
    icon: "local_pharmacy",
    url: "/category",
  },
  {
    id: "34-anglais-the_body",
    title: "Le corps",
    icon: "emoji_people",
    url: "/category",
  },
  {
    id: "35-anglais-at_the_doctor",
    title: "Chez le médecin",
    icon: "medical_services",
    url: "/category",
  },
  {
    id: "36-anglais-at_the_hospital",
    title: "À l'hôpital",
    icon: "emergency",
    url: "/category",
  },
  {
    id: "37-anglais-at_home",
    title: "À la maison",
    icon: "home",
    url: "/category",
  },
  {
    id: "38-anglais-in_the_house",
    title: "Dans la maison",
    icon: "bedroom_parent",
    url: "/category",
  },
  {
    id: "39-anglais-the_backyard",
    title: "Le jardin",
    icon: "grass",
    url: "/category",
  },
  {
    id: "40-anglais-pets",
    title: "Animaux domestiques",
    icon: "pets",
    url: "/category",
  },
  {
    id: "41-anglais-post_office_and_bank",
    title: "Poste et banque",
    icon: "account_balance",
    url: "/category",
  },
  {
    id: "42-anglais-services",
    title: "Services",
    icon: "build",
    url: "/category",
  },
  {
    id: "43-anglais-to_come",
    title: "À venir",
    icon: "event_upcoming",
    url: "/category",
  },
  {
    id: "44-anglais-police_and_crime",
    title: "Police et crime",
    icon: "local_police",
    url: "/category",
  },
  {
    id: "45-anglais-leisure_time",
    title: "Temps libre",
    icon: "movie",
    url: "/category",
  },
  {
    id: "46-anglais-sport_and_hobbies",
    title: "Sport et loisirs",
    icon: "sports_soccer",
    url: "/category",
  },
  {
    id: "47-anglais-socializing",
    title: "Socialisation",
    icon: "group_add",
    url: "/category",
  },
];
