export const LANGUAGES = {
  malagasy: { name: "Malagasy", flag: "🇲🇬" },
  sakalava: { name: "Sakalava", flag: "🇲🇬" },
  kibushi: { name: "Kibushi", flag: "🇲🇬" },
  allemand: { name: "Allemand", flag: "🇩🇪" },
  anglais: { name: "Anglais", flag: "🇬🇧" },
  espagnol: { name: "Espagnol", flag: "🇪🇸" },
  italien: { name: "Italien", flag: "🇮🇹" },
  japonais: { name: "Japonais", flag: "🇯🇵" },
};

export const THEMES = [
  {
    id: "01-anglais-hello",
    title: "Bonjour",
    icon: "topic",
    url: "/category",
  },
  {
    id: "02-anglais-relatives",
    title: "Les proches",
    icon: "topic",
    url: "/category",
  },
  {
    id: "03-anglais-family",
    title: "Ma famille",
    icon: "topic",
    url: "/category",
  },
  {
    id: "04-anglais-have-be",
    title: "Avoir et être",
    icon: "topic",
    url: "/category",
  },
  {
    id: "05-anglais-in-the-cafe",
    title: "Au café",
    icon: "topic",
    url: "/category",
  },
  {
    id: "06-anglais-restaurant",
    title: "Au restaurant",
    icon: "topic",
    url: "/category",
  },
  {
    id: "07-anglais-want",
    title: "Vouloir",
    icon: "topic",
    url: "/category",
  },
  {
    id: "08-anglais-plats",
    title: "Les plats",
    icon: "topic",
    url: "/category",
  },
  {
    id: "09-anglais-day-month",
    title: "Les jours et les mois",
    icon: "topic",
    url: "/category",
  },
  {
    id: "10-anglais-time-numbers",
    title: "L'heure et les nombres",
    icon: "topic",
    url: "/category",
  },
  {
    id: "11-anglais-rdv",
    title: "Les Rendez-vous",
    icon: "topic",
    url: "/category",
  },
  {
    id: "12-anglais-on_the_telephone",
    title: "Au téléphone",
    icon: "topic",
    url: "/category",
  },
  {
    id: "13-anglais-at_the_ticket_office",
    title: "À la billetterie",
    icon: "topic",
    url: "/category",
  },
  {
    id: "14-anglais-to_go_and_to_take",
    title: "Aller et prendre",
    icon: "topic",
    url: "/category",
  },
  {
    id: "15-anglais-public _transportation",
    title: "Public  transportation",
    icon: "directions_bus",
    url: "/category",
  },
  {
    id: "16-anglais-on_the_road",
    title: "Sur la route",
    icon: "topic",
    url: "/category",
  },
  {
    id: "17-anglais-about_town",
    title: "En ville",
    icon: "topic",
    url: "/category",
  },
  {
    id: "18-anglais-finding_your_way",
    title: "S'orienter",
    icon: "topic",
    url: "/category",
  },
  {
    id: "19-anglais-sightseeing",
    title: "Visites touristiques",
    icon: "topic",
    url: "/category",
  },
  {
    id: "20-anglais-at_the_airport",
    title: "À l'aéroport",
    icon: "topic",
    url: "/category",
  },
  {
    id: "21-anglais-booking_a_room",
    title: "Réserver une chambre",
    icon: "topic",
    url: "/category",
  },
  {
    id: "22-anglais-in_the_hotel",
    title: "À l'hôtel",
    icon: "topic",
    url: "/category",
  },
  {
    id: "23-anglais-camping",
    title: "Camping",
    icon: "topic",
    url: "/category",
  },
  {
    id: "24-anglais-descriptions",
    title: "Descriptions",
    icon: "topic",
    url: "/category",
  },
  {
    id: "25-anglais-shopping",
    title: "Achats",
    icon: "topic",
    url: "/category",
  },
  {
    id: "26-anglais-at_the_market",
    title: "Au marché",
    icon: "topic",
    url: "/category",
  },
  {
    id: "27-anglais-at_the_supermarket",
    title: "Au supermarché",
    icon: "topic",
    url: "/category",
  },
  {
    id: "28-anglais-clothes and shoes",
    title: "Vêtements et chaussures",
    icon: "topic",
    url: "/category",
  },
  {
    id: "29-anglais-jobs",
    title: "Emplois",
    icon: "topic",
    url: "/category",
  },
  {
    id: "30-anglais-the_office",
    title: "Au bureau",
    icon: "topic",
    url: "/category",
  },
  {
    id: "31-anglais-academic_world",
    title: "Monde académique",
    icon: "topic",
    url: "/category",
  },
  {
    id: "32-anglais-in_business",
    title: "Dans les affaires",
    icon: "topic",
    url: "/category",
  },
  {
    id: "33-anglais-at_the_pharmacy",
    title: "À la pharmacie",
    icon: "topic",
    url: "/category",
  },
  {
    id: "34-anglais-the_body",
    title: "Le corps",
    icon: "topic",
    url: "/category",
  },
  {
    id: "35-anglais-at_the_doctor",
    title: "Chez le médecin",
    icon: "topic",
    url: "/category",
  },
  {
    id: "36-anglais-at_the_hospital",
    title: "À l'hôpital",
    icon: "topic",
    url: "/category",
  },
  {
    id: "37-anglais-at_home",
    title: "À la maison",
    icon: "topic",
    url: "/category",
  },
  {
    id: "38-anglais-in_the_house",
    title: "Dans la maison",
    icon: "topic",
    url: "/category",
  },
  {
    id: "39-anglais-the_backyard",
    title: "Le jardin",
    icon: "topic",
    url: "/category",
  },
  {
    id: "40-anglais-pets",
    title: "Animaux domestiques",
    icon: "topic",
    url: "/category",
  },
  {
    id: "41-anglais-post_office_and_bank",
    title: "Poste et banque",
    icon: "topic",
    url: "/category",
  },
  {
    id: "42-anglais-services",
    title: "Services",
    icon: "topic",
    url: "/category",
  },
  {
    id: "43-anglais-to_come",
    title: "À venir",
    icon: "topic",
    url: "/category",
  },
  {
    id: "44-anglais-police_and_crime",
    title: "Police et crime",
    icon: "topic",
    url: "/category",
  },
  {
    id: "45-anglais-leisure_time",
    title: "Temps libre",
    icon: "topic",
    url: "/category",
  },
  {
    id: "46-anglais-sport_and_hobbies",
    title: "Sport et loisirs",
    icon: "sports_soccer",
    url: "/category",
  },
  {
    id: "47-anglais-socializing",
    title: "Socialisation",
    icon: "topic",
    url: "/category",
  },
];
